### ISSUE TITLE
local encrypted at Ubuntu 22.04 -  no attribute 'isAlive'. Did you mean: 'is_alive'?

### ISSUE THREAD

**Issue by olegpoltora** [bit-team/backintime#1427]
After updating Ubuntu to 22.04 I can't use "local encrypted"
I don't get any error in GUI, but in log I see:
AttributeError: 'TempPasswordThread' object has no attribute 'isAlive'. Did you mean: 'is_alive'?

and I get mount in .local/share/backintime/...

I have been using backintime with encrypting at Ubuntu 18.04 during last five years and all was ok.

backintime-qt --version
backintime-qt 1.2.1

P.S.
backintime --diagnostics
backintime: error: Unknown Argument(s): --diagnostics

**Comment by buhtz** [comment]
Dear Oleg,

thanks for reporting this. Bit 1.2.1 is very old.

Where do you installed BIT from? From Ubuntu universe repo or from the PPA at Launchpad?

Upgrading Ubuntu from 18.04 to 22.04 is from very old to not so old. I know that 22.04 is the current latest LTS. Be aware that the LTS is restricted to the "main" repos only. BIT does exist in universe and is outdated and unsuported.

Please read our README.md here at Microsoft GitHub.
I would suggest to install the latest BIT from PPA and try again.

**Comment by buhtz** [comment]
It was fixed with PR #1134 in 19th February 2021 and release with version 1.3.0 (see [changelog entry](https://github.com/bit-team/backintime/blob/4c6a9777a97f621c94e74692ce2eb05bd4aae1ea/CHANGES#L47)).

It is related to Pythons own `threading.Thread` class. That method is [deprecated since Python 3.8](https://docs.python.org/3/whatsnew/3.8.html?highlight=isalive) and [removed in Python 3.9](https://docs.python.org/3/whatsnew/3.9.html?highlight=isAlive#removed).
