### ISSUE TITLE
backintime -b Fails on CentOS 5.3

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#295]
Cent_OS 5.3
python-2.4.3-24.el5_3.6,i386

{harry-linux:goldsh:~}: backintime -b
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 27, in ?
    import snapshots
  File "/usr/share/backintime/common/snapshots.py", line 35, in ?
    import pluginmanager
  File "/usr/share/backintime/common/pluginmanager.py", line 51
    class PluginManager():
                                     ^
SyntaxError: invalid syntax

Caret is under the right paren ")"
____________________________________
OK, I got it working on CentOS 5.3, python 2.4.3.  Here's what I had to do:

1. Delete the () after class PluginManager
2. backintime-gnome looks like it's got too many problems for me to fix, so I copied a configuration from a FC11 system and modified the configuration by hand.
3. Put a copy of the backintime crontab @hourly entry in my crontab, by hand.

Everything seems to be working.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2009-09-08T18:24:52Z
 * owner: goldsh
 * assignee: bratdaking
 * the launchpad url was https://bugs.launchpad.net/bugs/426400

**Comment by Germar** [comment]
(by bratdaking)
I wonder, is this due to python 2.4? You have it also working on FC11 (python 2.6?), and you do not get these errors right?

**Comment by Germar** [comment]
(by oernii)
Same here on Centos 5.4 (python 2.4)

**Comment by Germar** [comment]
(by campitellian)
Ok... so you fixed your  PluginManager: and you still getting errors like:


(backintime:30337): libglade-WARNING **: unknown property `has_tooltip' for class `GtkLabel'

(backintime:30337): libglade-WARNING **: unknown property `has_tooltip' for class `GtkStatusbar'
Traceback (most recent call last):
  File "./app.py", line 1056, in ?
    main_window = MainWindow( cfg, app_instance )
  File "./app.py", line 238, in __init__
    self.special_background_color = gtk.gdk.Color( (2 * bg1.red + bg2.red) / 3, (2 * bg1.green + bg2.green) / 3,(2 * bg1.blue + bg2.blue) / 3 ).to_string()
AttributeError: 'gtk.gdk.Color' object has no attribute 'to_string

-----------------------------------------------------------------------------------------------------

Well don't worry I've fixed these problems too :P...  fixed for centos5.4 (should work for 5.3 etc too..)

Use the attached patch and apply it as per normal.

i.e copy the patch into the directory above the source code then do.
 patch -p0 < backintime-0.9.26_centosfix.patch 

With regards to centos and back in time there are  3 problems:

1) class PluginManager(): - problem as described above with python2.4
2) Problem with gtk.gdk.Color.to_string() - doesn't exist in the version of pygtk with centos
   (used to set the background color of the text in the UI)
3) Problem with lbl_snapshot.set_tooltip_text - doesn't exist in the version of pygtk with centos
   (i just made it not show the tooltip. it doesn't tell you anything you cant see already)

**Comment by Germar** [comment]
(by huygens-25)
Just to let you know that this solved my problem too on Red Hat Enterprise Linux (RHEL) 5.3

**Comment by Germar** [comment]
(by danleweb)
OK, fix commited. Thanks
