### ISSUE TITLE
ERROR: Failed to load plugin qt4plugin.py

### ISSUE THREAD

**Issue by daedator** [bit-team/backintime#702]
I had mostly working 1.1.2 installation until today. 
After upgrade to 1.2.0.alpha0 I have this error message when running any CLI command:
`ERROR: Failed to load plugin qt4plugin.py: module 'tools' has no attribute 'check_x_server'.`
It looks though that the program works - and claims to create new snapshots.

Besides GUI now fails to load at all...

**Comment by Germar** [comment]
Did you build manually from source? Looks like you forgot to build `qt` package. Please go to `backintime/qt` and run `./configure && make && make install`

**Comment by daedator** [comment]
Thanks, Germar! I have no error message now. 
I now see the qt install instruction at [https://github.com/bit-team/backintime/blob/master/README.md](url). Perhaps I overlooked it the first time.

**Comment by Germar** [comment]
No worries
