### ISSUE TITLE
Issue with new SSH proxy settings overwriting the default port

### ISSUE THREAD

**Issue by hannes101** [bit-team/backintime#1815]
I am testing backintime 1.5.0 for an update in fedora. I noticed that I couldn't ping my local NAS. Checking the logs I found out why.
Please see the settings here:
![image](https://github.com/user-attachments/assets/3a2c2e4c-9cff-4f47-90cc-6275bc666de7)
As you can see, actually it should connect using port 21212, however, when checking the logs, it is using port 22, which is set by the proxy settings.
```
DEBUG: [common/tools.py:1342 keyringSupported] Found appropriate keyring 'keyring.backends.chainer'
DEBUG: [common/tools.py:1271 keyringSupported] Keyring config file folder: /home/johannes/.config/python_keyring
DEBUG: [common/tools.py:1285 keyringSupported] Available keyring backends:
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.fail.Keyring (priority: 0)
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.SecretService.Keyring (priority: 5)
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.libsecret.Keyring (priority: 4.8)
DEBUG: [common/tools.py:1288 keyringSupported] keyring.backends.chainer.ChainerBackend (priority: 10)
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backends.Gnome.Keyring not found: AttributeError("module 'keyring.backends' has no attribute 'Gnome'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backends.kwallet.Keyring not found: AttributeError("module 'keyring.backends.kwallet' has no attribute 'Keyring'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backend.SecretServiceKeyring not found: AttributeError("module 'keyring.backend' has no attribute 'SecretServiceKeyring'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backend.GnomeKeyring not found: AttributeError("module 'keyring.backend' has no attribute 'GnomeKeyring'")
DEBUG: [common/tools.py:1330 keyringSupported] Metaclass keyring.backend.KDEWallet not found: AttributeError("module 'keyring.backend' has no attribute 'KDEWallet'")
DEBUG: [common/tools.py:1339 keyringSupported] Available supported backends: [<class 'keyring.backends.SecretService.Keyring'>, <class 'keyring.backends.kwallet.DBusKeyring'>, <class 'keyring.backends.chainer.ChainerBackend'>]
DEBUG: [common/tools.py:1342 keyringSupported] Found appropriate keyring 'keyring.backends.chainer'
DEBUG: [common/sshtools.py:293 SSH.startSshAgent] ssh-agent already running. Skip starting a new one.
DEBUG: [common/sshtools.py:448 SSH.unlockSshAgent] Private key /home/johannes/.ssh/2019QnapNAS is already unlocked in ssh agent
DEBUG: [common/sshtools.py:725 SSH.checkPingHost] Check ping host "192.168.178.45:22"
DEBUG: [common/sshtools.py:756 SSH.checkPingHost] Ping 192.168.178.45 failed. Host is down or wrong address.
```
A workaround for that is to enable the proxy settings
![image](https://github.com/user-attachments/assets/a6de866f-0655-4449-9cec-d8a7d2015a61)

and then it connects with the desired port 21212. Please see the attached log file.
[backintime_logs.txt](https://github.com/user-attachments/files/16400163/backintime_logs.txt)

My guess is that it's caused by https://github.com/bit-team/backintime/pull/1688

**Comment by buhtz** [comment]
Thank you for testing and reporting. Looks like a candidate for a quick and new release 1.5.1.

**Comment by buhtz** [comment]
[backintime-1.5.1-dev.tar.gz](https://github.com/user-attachments/files/16400302/backintime-1.5.1-dev.tar.gz)

Should be fixed. I checked it on a VM and my productive machine. Would you like to give it a try with that tarball before I prepare a new release?

**Comment by hannes101** [comment]
Yes, fixed now with 1.5.1-dev.
[backintime_logs.txt](https://github.com/user-attachments/files/16400324/backintime_logs.txt)

**Comment by buhtz** [comment]
Thank you very much for testing.

I am assuming that you will do some further tests with your rpm packaging?
Hope not but you might find something else. :biohazard:  Because of that I will wait with the next release until you give me green light, OK? :green_circle:

**Comment by hannes101** [comment]
I am just testing it locally for my personal backup, I think there's not much more I can do now.

**Comment by hannes101** [comment]
In fedora the package will be in updates-testing for, normally 7 days, I can extend that a bit and we see if things come up.

**Comment by buhtz** [comment]
Thank you for this offer, but this violates another Deadline. I need to reach Ubuntus DebianPackageFreeze.
