### ISSUE TITLE
'SettingsDialog' object has no attribute 'cbCopyUnsafeLinks'

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#2279]
### Problem
BIT crash and give an error message about missing attribute `cbCopyUnsafeLinks`.

### Reproduce
_Include_ Tab in _Manage profiles_ dialog. Try to add a directory or file that **is a symlink**.

### Background
Introduced in commit f94f5e3 and released with version 1.5.3 (Nov, 2024).

The bug is nearly 11 months old. I am not aware of any report about it. It is a minor GUI bug. No damage or data lose. With current state of knowledge I decide not to introduce a fix in current Debian stable (13).

### Error
```
Traceback (most recent call last):
  File "/usr/share/backintime/qt/manageprofiles/tab_include.py", line 185, in btn_include_add_clicked
    self._parent_dialog.cbCopyUnsafeLinks.isChecked() or
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SettingsDialog' object has no attribute 'cbCopyUnsafeLinks'
```
